### ISSUE TITLE
[ FEATURE ] Movie Scrapper Api Implementation

### ISSUE THREAD

**Issue by OshekharO** [Mehdi-Zandian/netflix-clone#1]
Hii if possible implement movie Scrapper and search function in this webapp.

For Example whenever any one click on movie poster it should show movie fetched from Scrapper Api instead of trailer.

Some Excellent Movie Scrapper Api:

https://www.2embed.ru/embed/tmdb/movie?id={{ tmdb_id }}

https://apimdb.net/e/tmdb/movie/{{ tmdb_id }}

https://dbgo.fun/video.php?id={{ imdb_id }}

https://api.123movie.cc/imdb.php?imdb={{ imdb_id }}&server=streamtape

https://vidsrc.me/embed/{{ imdb_id }}

Hope you will implement it soon.

**Comment by OshekharO** [comment]
Although I don't know much about this but checkout these it may help you:

https://github.com/twobin/react-lazyload
https://stackoverflow.com/search?q=Lazy+loading+images+javascript
https://github.com/pontusab/react-native-image-manipulator
https://stackoverflow.com/questions/46353020/how-to-resize-image-before-fetching-it
https://stackoverflow.com/questions/70056876/how-can-i-reduce-compress-image-size-in-axios-fetch-react-native

These are some best of things which I can find.

**Comment by Mehdi-Zandian** [comment]
I'll check them, Thanks a lot 🙏.
